projects:
  example:
    project_root: config/example/
    default_environment: dev
    environment:
      dev:
        type: postgresql
        connection:
          host: localhost
          port: 5432
          username: USERNAME
          password: USER_PASSWORD
          database: DATABASE_NAME
          schema: public
      
      prod:
        type: postgresql
        connection:
          host: HOSTNAME
          port: 5432
          username: USERNAME
          password: USER_PASSWORD
          database: DATABASE_NAME
          schema: public
